#!/bin/bash

set -eo pipefail

SERVICE=terraform-credentials

usage() {
  echo "Usage: $0 [get|store|forget] hostname" >&2
  exit 1
}

if [ $# -ne 2 ]; then
  usage
fi

case "$1" in
  get)
    token=$(security -q find-generic-password -s "$SERVICE" -a "$2" -w)
    cat <<EOF
{
    "token": "${token}"
}
EOF
    ;;
  store)
    token=$(jq -r 'if keys == ["token"] then .token else empty end')
    if [ -z "$token" ]; then
      echo "Unknown credentials object format" >&2
      exit 2
    fi
    security -q add-generic-password -U -s "$SERVICE" -a "$2" -w "$token"
    ;;
  forget)
    security -q delete-generic-password -s "$SERVICE" -a "$2" >/dev/null
    ;;
  *)
    usage
esac
